# Generated by Django 2.2.6 on 2022-05-17 19:34

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='last_login',
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 5, 17, 19, 34, 37, 885177, tzinfo=utc)),
        ),
    ]
